walking_controller:
  type: walking_controller/ReemcControl
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  left_ft_sensor: left_ankle_ft
  right_ft_sensor: right_ankle_ft
  base_imu_sensor: base_imu
  check_mode: True

  actuators:
    - leg_left_1_motor
    - leg_left_2_motor
    - leg_left_3_motor
    - leg_left_4_motor
    - leg_left_5_motor
    - leg_left_6_motor
    - leg_right_1_motor
    - leg_right_2_motor
    - leg_right_3_motor
    - leg_right_4_motor
    - leg_right_5_motor
    - leg_right_6_motor
