ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_inertia: 8.60398e-05
motor_torque_constant: 0.106
torque_sensor_offset: 0.0
reduction_ratio: 100
actuator_names:
  - arm_left_3_motor
check_mode: false
static_friction: 0.5
viscous_friction: 0.27
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
