ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_inertia: 0.000195461
motor_torque_constant: 0.065
torque_sensor_offset: 0.0
reduction_ratio: 144
actuator_names:
  - leg_left_4_motor
check_mode: false
static_friction: 0.1
viscous_friction: 0.4
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
