ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_inertia: 8.60398e-05
motor_torque_constant: 0.106
torque_sensor_offset: -2.3
reduction_ratio: 101
actuator_names:
  - leg_left_6_motor
check_mode: false
static_friction: 0.1
viscous_friction: 0.2
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
