play_motion:
  controllers: [right_arm_controller, left_arm_controller, left_leg_controller, right_leg_controller,
    head_controller, torso_controller]
  motions:
    hands_front:
      joints: [arm_right_3_joint, arm_right_4_joint, arm_right_1_joint, arm_left_4_joint,
        arm_left_1_joint, arm_left_2_joint, arm_right_2_joint, arm_left_3_joint]
      points:
      - positions: [-1.0, 1.65, 1.2, 1.65, 1.2, 0.3, 0.3, -1.0]
        time_from_start: 0.0
    hands_up:
      joints: [torso_2_joint, arm_right_6_joint, arm_right_5_joint, arm_left_5_joint,
        torso_1_joint, arm_left_4_joint, head_2_joint, arm_right_2_joint, arm_left_3_joint,
        head_1_joint, arm_right_7_joint, arm_right_3_joint, arm_right_4_joint, arm_right_1_joint,
        arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, -0.5, -0.5, 0.0, 1.3, 0.34, 0.0, -1.6, 0.0, 0.0, -1.6,
          1.4, 1.2, 0.9, 0.2]
        time_from_start: 0.0
    home: # NOTE: arm_*_2_joint is nonzero!
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint,
        hand_left_thumb_joint, hand_left_index_joint, hand_left_middle_joint, hand_right_thumb_joint,
        hand_right_index_joint, hand_right_middle_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      meta:
        name: Home
        usage: posture
        description: Both arms down and completely stretched.
    home_legs:
      joints: [leg_left_1_joint, leg_left_2_joint, leg_left_3_joint, leg_left_4_joint,
               leg_left_5_joint, leg_left_6_joint,
               leg_right_1_joint, leg_right_2_joint, leg_right_3_joint,leg_right_4_joint,
               leg_right_5_joint, leg_right_6_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
    interact:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint,
        hand_left_thumb_joint, hand_left_index_joint, hand_left_middle_joint, hand_right_thumb_joint,
        hand_right_index_joint, hand_right_middle_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, -0.4, 0.25, -0.1, 0.6109, 0.0, 0.0, 0.0, -0.4,
          0.25, -0.1, 0.6109, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      meta:
        name: Interact
        usage: posture
        description: Same posture as in Hands Down.
    small_squat:
      joints: [leg_left_4_joint, leg_right_3_joint, leg_right_5_joint, leg_left_5_joint,
        leg_right_4_joint, leg_left_3_joint]
      points:
      - positions: [1.0, -0.5, -0.5, -0.5, 1.0, -0.5]
        time_from_start: 0.0
    test_motion:
      joints: [torso_2_joint, arm_right_6_joint, arm_right_5_joint, arm_left_5_joint,
        torso_1_joint, arm_left_4_joint, head_2_joint, arm_right_2_joint, arm_left_3_joint,
        head_1_joint, arm_right_7_joint, arm_right_3_joint, arm_right_4_joint, arm_right_1_joint,
        arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, -0.5, -0.5, 0.0, 1.3, 0.34, 0.0, -1.6, 0.0, 0.0, -1.6,
          1.4, 1.2, 0.9, 0.2]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 1.65, 0.0, 0.2, -1.0, 0.0, 0.0, -1.0,
          1.65, 1.2, 1.2, 0.3]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.0, 0.0, 0.5,
          0.5, 0.5, 0.5, 0.5]
        time_from_start: 3.0
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0]
        time_from_start: 6.0
    squat:
      joints: [arm_left_7_joint, leg_left_1_joint, arm_right_6_joint, torso_2_joint,
        arm_right_5_joint, arm_left_5_joint, arm_left_6_joint, arm_left_1_joint, torso_1_joint,
        arm_left_4_joint, head_2_joint, leg_right_3_joint, leg_left_2_joint, arm_right_2_joint,
        leg_left_6_joint, head_1_joint, leg_right_6_joint, arm_right_7_joint, arm_right_3_joint,
        leg_left_5_joint, leg_right_4_joint, arm_right_4_joint, arm_left_3_joint,
        leg_right_1_joint, leg_left_4_joint, leg_right_5_joint, arm_left_2_joint,
        arm_right_1_joint, leg_right_2_joint, leg_left_3_joint]
      points:
      - positions: [0.0, 0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.25, -1.35,
          0.0, 1.3, 0.0, 0.0, 0.0, 0.0, 0.0, -1.3, 2.6, 0.9, 0.0, 0.0, 2.6, -1.3,
          1.3, 0.0, 0.0, -1.35]
        time_from_start: 0.0
