motor_inertia: 0.000149069
static_friction_gain: 0.0
viscous_friction_gain: 0.4
global_friction_gain: 1.0
inertia_compensation_gain: 0.0
torque_derivative_feedback_gain: 0.0
velocity_friction_compensation_tolerance: 1e-2
feed_forward_acceleration_gain: 1.0

ripple_phase_offset: 0.0
ripple_amplitude: 0.0
ripple_compensation_gain: 0.0

acceleration_differentiator:
  initial_value: 0.
  order: 11
  
  differentiator_type: OneSide
  differentiator_order: FirstOrder

acceleration_filter_type: ButterworthFilterd
acceleration_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      
      cutoff1: 50.0
      cutoff2: 0.0

torque_sensor_filter_type: ButterworthFilterd
torque_sensor_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      
      cutoff1: 50.0
      cutoff2: 0.0

command_filter_type: ButterworthFilterd
command_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      
      cutoff1: 50.0
      cutoff2: 0.0
    - order: 5
      type: BandReject
      composition_type: Sequence
      
      cutoff1: 16.0
      cutoff2: 21.0
    - order: 5
      type: BandReject
      composition_type: Sequence
      
      cutoff1: 35.0
      cutoff2: 37.0

use_filtered_torque_sensor: true
use_filtered_acceleration: true
use_filtered_command: true
