motor_inertia: 0.000191658
static_friction_gain: 0.1
viscous_friction_gain: 0.3
global_friction_gain: 0.7
inertia_compensation_gain: 1.0
torque_derivative_feedback_gain: 0.0

ripple_phase_offset: 0.0
ripple_amplitude: 0.0
ripple_compensation_gain: 0.0

acceleration_differentiator:
  initial_value: 0.
  order: 5
  dt: 0.001
  differentiator_type: OneSide
  differentiator_order: FirstOrder

torque_differentiator:
  initial_value: 0.
  order: 5
  dt: 0.001
  differentiator_type: OneSide
  differentiator_order: FirstOrder

acceleration_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      freq: 1000.0
      cutoff1: 50.0
      cutoff2: 0.0

torque_sensor_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      freq: 1000.0
      cutoff1: 50.0
      cutoff2: 0.0

command_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      freq: 1000.0
      cutoff1: 50.0
      cutoff2: 0.0

torque_derivative_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      freq: 1000.0
      cutoff1: 50.0
      cutoff2: 0.0

use_filtered_torque_sensor: true
use_filtered_acceleration: true
use_filtered_command: true
